import React, { useEffect, useState } from "react";
import axios from "axios";

import Head from 'next/head'
import Image from 'next/image'
import MatchCard from "../components/MatchCard";

import styles from '../styles/Home.module.css'

export default function Home() {
  const [multiplayerMatchList, setMultiplayerMatchList] = useState([]);
  const gamertag = "shesjustaglitch";

  React.useEffect(() => {
    function getMultiplayerMatches() {
      const url = "https://halo.api.stdlib.com/infinite@0.3.3/stats/matches/list/";
      const token = "tok_dev_qYAJqr8JHrsXH8A2CuGWK4aK8Sc7TcEWSi8zKUSnbDSx8kXZvmMfzdX4nq1k89Mg";
      
      axios({
        url,
        method: "get",
        headers: {
          Authorization: `Bearer ${token}`
        },
        params: {
          gamertag: gamertag
        }
      })
        .then((response) => {
          setMultiplayerMatchList(response.data.data);
          // console.log(response.data.data);
        })
        .catch((err) => {
          console.log(err, "error");
        });
    }
    getMultiplayerMatches();
  });

  let matches = [];
  matches = multiplayerMatchList;

  return (
    <div className={styles.container}>
      <Head>
        <title>Halo Infinite Matches</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Halo Infinite Matches
        </h1>

        <ul className="card-list">
          {matches.map((match) => (
            <MatchCard
              id={match.id}
              map={match.details.map.name}
              background={match.details.map.asset.thumbnail_url}
              mode={match.details.category.name}
              outcome={match.player.outcome}
              playlist={match.details.playlist.name}
              date={match.played_at}
              player={gamertag}
            />
          ))}
        </ul>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
