import React, { useEffect, useState } from "react";
import axios from "axios";

import Head from 'next/head'
import Image from 'next/image'

import styles from '../../styles/Home.module.css'
import { useRouter } from 'next/router';

export default function Player() {

  const { asPath } = useRouter();

  console.log(asPath);

  return (
    <div className={styles.container}>
      <Head>
        <title>Halo Infinite Matches - Match</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Player
        </h1>

      </main>
    </div>
  )
}
